#ifndef GAME_PARAMS
#define GAME_PARAMS

#define FOREVER 1
#define PANOU_CONTROL_H 5
#define PANOU_JOC_H 20
#define PADDING_LEFT 5
#define PADDING_MIDDLE 10
#define TIMER_SECONDS 30

#define MENU_WINDOW_HEIGHT 50
#define MENU_ITEMS_PADDING 10
#define MENU_NUMBER_OF_OPTIONS 6

#define NR_OF_PLAYERS 5
#define MAX_MESSAGE_LENGTH 200

#define PAUSE_MENU_HEIGHT 5
#define PAUSE_MENU_WIDTH 40
#define PAUSE_MENU_X 3
#define PAUSE_MENU_y 3
#endif // GAME_PARAMS